const state={data:null,run:null,page:'today'};
const q=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v===null||v===undefined?'—':Number(v).toFixed(2);const zhDir=v=>({bullish:'看涨',bearish:'看跌',neutral:'中性',unavailable:'不可用',not_applicable:'当天不适用'})[v]||v||'—';
function notice(text,bad=false){const n=q('#notice');n.textContent=text;n.classList.remove('hidden');n.style.background=bad?'#fbeaea':'#e5f6ef';n.style.color=bad?'#8f2f2f':'#126448';setTimeout(()=>n.classList.add('hidden'),5000)}
async function api(name,...args){const r=await window.pywebview.api[name](...args);if(!r.ok)throw new Error(r.error||'操作失败');return r.value}
function metric(label,value){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function renderToday(){const d=state.data.dashboard,l=d.latest,cal=state.data.calendar;const hero=l?`<div><p class="eyebrow">${esc(l.trade_date)} · ${esc(l.identity||'系统身份未记录')}</p><h2>${l.audit_valid?'审计记录完整':'审计未通过'}</h2><p>${esc(l.cutoff_et||'等待冻结证据')}</p></div><div class="big">${l.predictions.length}<small>正式预测</small></div>`:`<div><p class="eyebrow">${cal.is_session?'今日是交易日':'今日休市'}</p><h2>等待第一次桌面运行</h2><p>${cal.is_session?'可以开始或恢复今日模拟':'下一交易日 '+esc(cal.next_session)}</p></div><div class="big">0<small>运行记录</small></div>`;
 q('#today').innerHTML=`<div class="hero">${hero}</div><div class="metrics">${metric('候选',l?Object.keys(l.reports_by_symbol).length:0)}${metric('正式预测',l?l.predictions.length:0)}${metric('模拟订单',l?l.orders.length:0)}${metric('当前状态',l?l.status:'未开始')}</div>${l?runDetail(l):'<div class="card empty">首次设置完成后，点击“开始 / 恢复今日模拟”。</div>'}`}
function detailId(runId){return 'candidate-detail-'+String(runId||'none').replace(/[^A-Za-z0-9_-]/g,'-')}
function runDetail(l){const symbols=Object.keys(l.reports_by_symbol||{});const preds=l.predictions||[];const timeline=Object.entries(l.workflow?.stages||{}).map(([k,v])=>`<div class="timeline-row"><i></i><span>${esc(v.observed_at_et?.slice(11,19)||'')}</span><b>${esc(k)} · ${esc(v.status)}</b></div>`).join('')||'<div class="empty">流程时间线尚未形成</div>';const prediction=preds.map(p=>`<span class="pill ${p.direction}">${esc(p.symbol)} · ${zhDir(p.direction)}</span>`).join('')||'<span class="pill neutral">空榜：没有凑票</span>';const cards=symbols.map(s=>`<button class="candidate" onclick="showCandidate('${esc(s)}','${esc(l.run_id)}')"><strong>${esc(s)}</strong><span>${esc(l.integration_audit_by_symbol?.[s]?.published?'已发布':'未通过门禁')}</span></button>`).join('')||'<div class="empty">没有候选</div>';return `<div class="grid-2"><div class="card"><h3>六领域候选</h3><div class="candidate-list">${cards}</div><div id="${detailId(l.run_id)}"></div></div><div class="card"><h3>流程时间线</h3><div class="timeline">${timeline}</div></div></div><div class="card" style="margin-top:18px"><h3>冻结结果</h3><div class="pills">${prediction}</div></div>`}
window.showCandidate=function(symbol,runId){const latest=state.data.dashboard.latest;const l=latest?.run_id===runId?latest:state.run;const reports=l?.reports_by_symbol?.[symbol]||[];const domains=reports.map(r=>`<article class="domain"><h4>${esc(r.domain)} · ${zhDir(r.verdict)}</h4><p><b>支持：</b>${esc(r.thesis)}</p><p class="counter"><b>反方：</b>${esc(r.antithesis)}</p><p><b>不知道：</b>${esc((r.unknowns||[]).join('；')||'无')}</p></article>`).join('');const audit=l?.integration_audit_by_symbol?.[symbol]||{};q('#'+detailId(runId)).innerHTML=`<div class="detail-bar"><h3>${esc(symbol)} 的完整分析</h3><span class="status ${audit.published?'ok':''}">${audit.published?'进入正式榜':'门禁未通过'}</span></div><div class="domains">${domains}</div>`}
function renderHistory(){const rows=state.data.dashboard.runs.map(r=>`<tr class="clickable" onclick="selectRun('${esc(r.run_id)}')"><td>${esc(r.trade_date)}</td><td>${esc(r.mode)}</td><td>${r.candidate_count}</td><td>${r.prediction_count}</td><td>${r.order_count}</td><td><span class="status ${r.audit_valid?'ok':'bad'}">${r.audit_valid?'完整':'失败'}</span></td></tr>`).join('')||'<tr><td colspan="6">尚无历史记录</td></tr>';q('#history').innerHTML=`<div class="card"><h3>不可变运行记录</h3><table class="table"><thead><tr><th>日期</th><th>模式</th><th>候选</th><th>预测</th><th>订单</th><th>审计</th></tr></thead><tbody>${rows}</tbody></table><div id="history-detail"></div></div>`}
window.selectRun=async function(id){try{const l=await api('get_run',id);state.run=l;q('#history-detail').innerHTML=`<div class="detail-bar"><h3>${esc(id)}</h3><div><button class="secondary" onclick="openRun('${esc(id)}','run_replay.html')">打开完整回放</button></div></div>${runDetail(l)}`}catch(e){notice(e.message,true)}}
window.openRun=async function(id,name){try{await api('open_run_file',id,name)}catch(e){notice(e.message,true)}}
function renderHoldings(){const l=state.data.dashboard.latest;const pos=(l?.positions||[]).map(p=>`<tr><td>${esc(p.symbol)}</td><td>${fmt(p.quantity)}</td><td>${fmt(p.average_cost)}</td><td>${esc(p.origin||'本次系统')}</td></tr>`).join('')||'<tr><td colspan="4">没有当前持仓记录</td></tr>';const trips=(l?.round_trips||[]).map(r=>`<tr><td>${esc(r.symbol)}</td><td>${fmt(r.entry_fill)}</td><td>${fmt(r.exit_fill)}</td><td>${fmt(r.fees)}</td><td>${fmt(r.net_pnl)}</td></tr>`).join('')||'<tr><td colspan="5">没有完整成交回合</td></tr>';q('#holdings').innerHTML=`<div class="grid-2"><div class="card"><h3>最近一次持仓快照</h3><table class="table"><tr><th>股票</th><th>数量</th><th>成本</th><th>来源</th></tr>${pos}</table></div><div class="card"><h3>实际模拟成交</h3><table class="table"><tr><th>股票</th><th>开仓</th><th>退出</th><th>费用</th><th>净盈亏</th></tr>${trips}</table></div></div>`}
function renderPerformance(){const t=state.data.dashboard.totals,p=state.data.dashboard.performance||{},sectors=Object.entries(p.sector_predictions||{}).map(([name,count])=>`<span class="pill neutral">${esc(name)} · ${count}</span>`).join('')||'<span class="pill neutral">尚无行业暴露</span>';q('#performance').innerHTML=`<div class="metrics">${metric('累计净盈亏',fmt(t.net_pnl))}${metric('累计费用',fmt(t.fees))}${metric('最大回撤',fmt(p.maximum_drawdown))}${metric('正式预测',t.predictions)}</div><div class="grid-2"><div class="card"><h3>多空暴露</h3><div class="metrics compact">${metric('看涨',p.long_predictions||0)}${metric('看跌',p.short_predictions||0)}</div></div><div class="card"><h3>行业分布</h3><div class="pills">${sectors}</div></div></div><div class="card" style="margin-top:18px"><h3>当前阶段的含义</h3><p>这里累计的是实际模拟成交到实际模拟成交的盈亏与费用；预测成绩仍按官方开盘到收盘单独核验。当前一股模拟阶段只用于验证流程和成本，不冒充已验证的盈利能力。</p></div>`}
function renderHealth(extra=null){const h=extra||state.data.dashboard.health||{};const items=Object.entries(h).filter(([k])=>!['schema_version'].includes(k)).map(([k,v])=>`<div class="health-item"><span>${esc(k)}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')||'<div class="empty">点击右上角“系统检查”进行实时检查</div>';q('#health').innerHTML=`<div class="card"><h3>连接与后台状态</h3><div class="health-grid">${items}</div></div>`}
function renderSettings(){const s=state.data.settings;q('#settings').innerHTML=`<div class="grid-2"><div class="card"><h3>运行设置</h3><p>AI：${esc(s.ai_backend)} · ${esc(s.model)}</p><p>OpenD：${esc(s.opend_host)}:${esc(s.opend_port)}</p><p>每日启动：${esc(s.automatic_start_et)} ET</p><p>自动值守：${s.automatic_run_enabled?'已启用':'未启用'}</p><div class="settings-actions"><button class="primary" id="auto-on">启用每日自动模拟</button><button class="secondary" id="auto-off">停止后续自动运行</button><button class="secondary" id="edit-setup">修改设置</button></div></div><div class="card"><h3>教授版导出</h3><p>导出内容自动隐藏账户、密钥、本地路径与原始付费行情。</p><button class="secondary" id="export">导出静态报告</button></div></div>`;q('#auto-on').onclick=async()=>action('enable_automatic','自动值守已启用');q('#auto-off').onclick=async()=>action('disable_automatic','已停止后续自动运行');q('#edit-setup').onclick=()=>q('#setup').classList.remove('hidden');q('#export').onclick=async()=>action('export_report','教授报告已导出')}
async function action(name,message){try{await api(name);notice(message);await load()}catch(e){notice(e.message,true)}}
function showPage(page){state.page=page;document.querySelectorAll('.page,.nav').forEach(e=>e.classList.remove('active'));q('#'+page).classList.add('active');q(`.nav[data-page="${page}"]`).classList.add('active');q('#page-title').textContent={today:'今天',history:'历史回放',holdings:'持仓与成交',performance:'组合表现',health:'系统健康',settings:'设置与导出'}[page]}
function fillSetup(){const s=state.data.settings;const form=q('#setup-form');for(const name of ['ai_backend','model','sec_identity','opend_host','opend_port','automatic_start_et']){if(form.elements[name]&&s[name]!==undefined)form.elements[name].value=s[name]}if(form.elements.universe_file)form.elements.universe_file.value=s.universe_file||s.suggested_universe_file||''}
function render(){renderToday();renderHistory();renderHoldings();renderPerformance();renderHealth();renderSettings();fillSetup();const service=state.data.dashboard.health?.state||'桌面已连接';q('#service-text').textContent=service;q('#service-dot').className='dot '+(service.includes('failed')||service.includes('error')?'bad':'ok');if(!state.data.settings.setup_complete)q('#setup').classList.remove('hidden')}
async function load(){try{state.data=await api('get_state');render()}catch(e){notice(e.message,true)}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));q('#run-button').onclick=async()=>action('run_today','今日模拟任务已经启动或连接');q('#doctor-button').onclick=async()=>{try{const v=await api('doctor');showPage('health');renderHealth(v)}catch(e){notice(e.message,true)}};
q('#setup-form').onsubmit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target).entries());payload.opend_port=Number(payload.opend_port);try{await api('save_setup',payload);q('#setup').classList.add('hidden');q('#setup-error').textContent='';await load();notice('首次设置已保存')}catch(err){q('#setup-error').textContent=err.message}};
q('#choose-universe').onclick=async()=>{try{const picked=await api('choose_universe');if(picked.file)q('#setup-form').elements.universe_file.value=picked.file}catch(err){q('#setup-error').textContent=err.message}};
window.addEventListener('pywebviewready',load);setInterval(()=>{if(state.data)load()},30000);
